#!/bin/bash
./spl ../../os_lab/stage_27/os_startup/os_code.spl
./spl ../../os_lab/stage_27/exception/exc_int.spl
./spl ../../os_lab/stage_27/hardware_interrupts/console_interrupt.spl
./spl ../../os_lab/stage_27/hardware_interrupts/disk_interrupt.spl
./spl ../../os_lab/stage_27/hardware_interrupts/timer_interrupt.spl
./spl ../../os_lab/stage_27/modules/resource_manager.spl
./spl ../../os_lab/stage_27/modules/process_manager.spl
./spl ../../os_lab/stage_27/modules/memory_manager.spl
./spl ../../os_lab/stage_27/modules/file_manager.spl
./spl ../../os_lab/stage_27/modules/device_manager.spl
./spl ../../os_lab/stage_27/modules/scheduler.spl
./spl ../../os_lab/stage_27/modules/pager_mod.spl
./spl ../../os_lab/stage_27/modules/boot_mod.spl
./spl ../../os_lab/stage_27/software_interrupts/int_4.spl
./spl ../../os_lab/stage_27/software_interrupts/int_5.spl
./spl ../../os_lab/stage_27/software_interrupts/read_call.spl
./spl ../../os_lab/stage_27/software_interrupts/write_call.spl
./spl ../../os_lab/stage_27/software_interrupts/fork_call.spl
./spl ../../os_lab/stage_27/software_interrupts/exec_call.spl
./spl ../../os_lab/stage_27/software_interrupts/int_10.spl
./spl ../../os_lab/stage_27/software_interrupts/int_11.spl
./spl ../../os_lab/stage_27/software_interrupts/int_12.spl
./spl ../../os_lab/stage_27/software_interrupts/int_13.spl
./spl ../../os_lab/stage_27/software_interrupts/int_14.spl
./spl ../../os_lab/stage_27/software_interrupts/shutdown_call.spl
./spl ../../os_lab/stage_27/software_interrupts/int_16.spl
./spl ../../os_lab/stage_27/software_interrupts/int_17.spl